name: reverb_focused

list:
  - reverb
  - background_noise
  - colored_noise
  - polarity_inversion
  - clip_distortion

configs:
  reverb:
    p: 0.5
    min_reverb: 30
    max_reverb: 100
    min_damp_factor: 30
    max_damp_factor: 100
    min_room_size: 30
    max_room_size: 100
    sample_rate: 16000

  background_noise:
    p: 1.0                # probability of applying this augmentation
    local_path: '/dtln/data/noises'
    min_snr_in_db: 3      # minimum SNR
    max_snr_in_db: 10     # maximum SNR for randomizer when adding background noise
    sample_rate: 16000

  polarity_inversion:
    p: 0.5

  clip_distortion:
    p: 0.8
    min_percent_threshold: 0
    max_percent_threshold: 15

  colored_noise:
    p: 0.0
    min_snr_in_db: 10
    max_snr_in_db: 20
    min_f_decay: -2.0
    max_f_decay: 2.0
    sample_rate: 16000